# Generated by Django 5.2.6 on 2025-09-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ("airplane_type", "rows", "seats_per_row")},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ("first_name", "last_name")},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ("-departure_time",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ("source", "destination")},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("flight", "row", "seat")},
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "flight"), name="unique_ticket"
            ),
        ),
    ]
